/**
 * Core types for the agent harness.
 *
 * Design principle: every entry point (CLI, API, Web) constructs a
 * HarnessRequest and feeds it to the Orchestrator. The orchestrator
 * plans a pipeline of AgentStep executions, each producing artifacts
 * that accumulate in a SharedContext. The final output is an
 * HarnessResult containing the generated HTML and metadata.
 */

import type { ComplexityPlan } from "./complexity.js";

// ─── Request / Result ────────────────────────────────────────────

export interface HarnessRequest {
  /** Unique run ID — generated by the entry point */
  id: string;
  /** Natural-language description of the page to build */
  prompt: string;
  /** Optional constraints the user wants enforced */
  constraints?: PageConstraints;
  /** Skip the validation step */
  skipValidation?: boolean;
  /** Optional callback for streaming progress updates */
  onProgress?: (event: ProgressEvent) => void;
}

export interface PageConstraints {
  /** e.g. "marketing-landing", "dashboard", "blog-post" */
  pageType?: string;
  /** Color palette preferences */
  palette?: string[];
  /** Typography preferences */
  fonts?: { heading?: string; body?: string };
  /** Responsive breakpoints to target */
  breakpoints?: number[];
  /** Maximum section count */
  maxSections?: number;
  /** Any raw style directives to pass through */
  customCSS?: string;
}

export interface HarnessResult {
  id: string;
  /** The final assembled HTML string (landing page for multi-page) */
  html: string;
  /** All pages keyed by page ID (present when tier is "multi") */
  pages?: Record<string, string>;
  /** Metadata about the generation run */
  meta: RunMeta;
  /** Accumulated data from agents (e.g. validation audit) */
  data: Record<string, unknown>;
}

export interface RunMeta {
  durationMs: number;
  agentSteps: AgentStepResult[];
  tokenUsage: { input: number; output: number };
}

// ─── Agent contract ──────────────────────────────────────────────

/**
 * Every agent implements this interface. The orchestrator doesn't
 * know or care what model the agent uses, whether it calls an LLM
 * or runs deterministic logic, or how it formats its output.
 * It only cares about the input/output shape.
 */
export interface Agent {
  /** Unique name used for logging and step references */
  name: string;
  /** Human-readable description */
  description: string;
  /**
   * Execute one step. Receives the full shared context (read-only
   * snapshot) and returns an artifact to merge back in.
   */
  execute(ctx: SharedContext, request: HarnessRequest): Promise<AgentOutput>;
}

export interface AgentOutput {
  /** The artifact key this agent produces (e.g. "layout", "styles") */
  artifactKey: string;
  /** The artifact value — typically a string of HTML/CSS/content */
  artifact: string;
  /** Optional structured data other agents might consume */
  data?: Record<string, unknown>;
  /** Token usage for this step */
  tokenUsage?: { input: number; output: number };
}

export interface AgentStepResult {
  agentName: string;
  artifactKey: string;
  durationMs: number;
  tokenUsage: { input: number; output: number };
}

// ─── Shared context ──────────────────────────────────────────────

/**
 * Accumulates artifacts as agents execute. Each agent can read
 * all previous artifacts and contribute its own. The orchestrator
 * controls mutation — agents receive a frozen snapshot.
 */
export interface SharedContext {
  /** The original request */
  request: HarnessRequest;
  /** Artifacts keyed by agent output key */
  artifacts: Record<string, string>;
  /** Structured data from agents, merged progressively */
  data: Record<string, unknown>;
  /** Complexity plan — set by the orchestrator before agents run */
  complexity?: ComplexityPlan;
}

// ─── Pipeline / orchestration ────────────────────────────────────

/**
 * A pipeline is an ordered list of steps. Steps at the same
 * `phase` number can run concurrently; phases execute sequentially.
 */
export interface Pipeline {
  steps: PipelineStep[];
}

export interface PipelineStep {
  /** Which agent to run */
  agentName: string;
  /** Phase number — lower runs first, same phase = parallel */
  phase: number;
  /** Optional condition: skip this step if false */
  condition?: (ctx: SharedContext) => boolean;
}

// ─── Progress events ─────────────────────────────────────────────

export type ProgressEvent =
  | { type: "pipeline_start"; pipeline: Pipeline }
  | { type: "agent_start"; agentName: string; phase: number }
  | { type: "agent_chunk"; agentName: string; chunk: string }
  | { type: "agent_complete"; agentName: string; result: AgentStepResult }
  | { type: "agent_artifact"; agentName: string; artifactKey: string; artifact: string }
  | { type: "design_tokens"; css: string }
  | { type: "pipeline_complete"; result: HarnessResult }
  | { type: "status"; message: string; detail?: StatusDetail }
  | { type: "error"; agentName?: string; error: string };

export type StatusDetail =
  | { kind: "complexity"; tier: "single" | "multi"; pages: { id: string; title: string; description: string; isLanding: boolean }[] }
  | { kind: "pipeline_plan"; phases: { phase: number; agents: string[] }[] }
  | { kind: "phase_start"; phase: number; agents: string[] }
  | { kind: "agent_progress"; agentName: string; message: string };
